// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7tUAyOKWrUq-emCwt8agXNOh367kQtnk',
    appId: '1:949174804898:web:d72cd9c9f62b84a5ed92fb',
    messagingSenderId: '949174804898',
    projectId: 'whatsap-4ba75',
    authDomain: 'whatsap-4ba75.firebaseapp.com',
    storageBucket: 'whatsap-4ba75.firebasestorage.app',
    measurementId: 'G-SYKNKKQ5RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAagRDfQFGJIcImfiTQDh10jAh70RwPrUY',
    appId: '1:949174804898:android:b61a76976d920a2fed92fb',
    messagingSenderId: '949174804898',
    projectId: 'whatsap-4ba75',
    storageBucket: 'whatsap-4ba75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflvKyPgasnDCn8yi4gO0veHDsOKRXCug',
    appId: '1:949174804898:ios:c8ec8308d3d3feceed92fb',
    messagingSenderId: '949174804898',
    projectId: 'whatsap-4ba75',
    storageBucket: 'whatsap-4ba75.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDflvKyPgasnDCn8yi4gO0veHDsOKRXCug',
    appId: '1:949174804898:ios:c8ec8308d3d3feceed92fb',
    messagingSenderId: '949174804898',
    projectId: 'whatsap-4ba75',
    storageBucket: 'whatsap-4ba75.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7tUAyOKWrUq-emCwt8agXNOh367kQtnk',
    appId: '1:949174804898:web:4453e372cdd8a4f4ed92fb',
    messagingSenderId: '949174804898',
    projectId: 'whatsap-4ba75',
    authDomain: 'whatsap-4ba75.firebaseapp.com',
    storageBucket: 'whatsap-4ba75.firebasestorage.app',
    measurementId: 'G-8VTHP5Q735',
  );
}
